/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraitsRouteImport } from './routes/traits'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as SmartPointersRouteImport } from './routes/smart-pointers'
import { Route as RunRouteImport } from './routes/run'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OwnershipRouteImport } from './routes/ownership'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MacrosRouteImport } from './routes/macros'
import { Route as LifetimesRouteImport } from './routes/lifetimes'
import { Route as FrontendRouteImport } from './routes/frontend'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as ConcurrencyRouteImport } from './routes/concurrency'
import { Route as AsyncRouteImport } from './routes/async'
import { Route as IndexRouteImport } from './routes/index'

const TraitsRoute = TraitsRouteImport.update({
  id: '/traits',
  path: '/traits',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartPointersRoute = SmartPointersRouteImport.update({
  id: '/smart-pointers',
  path: '/smart-pointers',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnershipRoute = OwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosRoute = MacrosRouteImport.update({
  id: '/macros',
  path: '/macros',
  getParentRoute: () => rootRouteImport,
} as any)
const LifetimesRoute = LifetimesRouteImport.update({
  id: '/lifetimes',
  path: '/lifetimes',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendRoute = FrontendRouteImport.update({
  id: '/frontend',
  path: '/frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcurrencyRoute = ConcurrencyRouteImport.update({
  id: '/concurrency',
  path: '/concurrency',
  getParentRoute: () => rootRouteImport,
} as any)
const AsyncRoute = AsyncRouteImport.update({
  id: '/async',
  path: '/async',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/async': typeof AsyncRoute
  '/concurrency': typeof ConcurrencyRoute
  '/errors': typeof ErrorsRoute
  '/frontend': typeof FrontendRoute
  '/lifetimes': typeof LifetimesRoute
  '/macros': typeof MacrosRoute
  '/memory': typeof MemoryRoute
  '/ownership': typeof OwnershipRoute
  '/playground': typeof PlaygroundRoute
  '/quiz': typeof QuizRoute
  '/run': typeof RunRoute
  '/smart-pointers': typeof SmartPointersRoute
  '/testing': typeof TestingRoute
  '/traits': typeof TraitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/async': typeof AsyncRoute
  '/concurrency': typeof ConcurrencyRoute
  '/errors': typeof ErrorsRoute
  '/frontend': typeof FrontendRoute
  '/lifetimes': typeof LifetimesRoute
  '/macros': typeof MacrosRoute
  '/memory': typeof MemoryRoute
  '/ownership': typeof OwnershipRoute
  '/playground': typeof PlaygroundRoute
  '/quiz': typeof QuizRoute
  '/run': typeof RunRoute
  '/smart-pointers': typeof SmartPointersRoute
  '/testing': typeof TestingRoute
  '/traits': typeof TraitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/async': typeof AsyncRoute
  '/concurrency': typeof ConcurrencyRoute
  '/errors': typeof ErrorsRoute
  '/frontend': typeof FrontendRoute
  '/lifetimes': typeof LifetimesRoute
  '/macros': typeof MacrosRoute
  '/memory': typeof MemoryRoute
  '/ownership': typeof OwnershipRoute
  '/playground': typeof PlaygroundRoute
  '/quiz': typeof QuizRoute
  '/run': typeof RunRoute
  '/smart-pointers': typeof SmartPointersRoute
  '/testing': typeof TestingRoute
  '/traits': typeof TraitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/async'
    | '/concurrency'
    | '/errors'
    | '/frontend'
    | '/lifetimes'
    | '/macros'
    | '/memory'
    | '/ownership'
    | '/playground'
    | '/quiz'
    | '/run'
    | '/smart-pointers'
    | '/testing'
    | '/traits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/async'
    | '/concurrency'
    | '/errors'
    | '/frontend'
    | '/lifetimes'
    | '/macros'
    | '/memory'
    | '/ownership'
    | '/playground'
    | '/quiz'
    | '/run'
    | '/smart-pointers'
    | '/testing'
    | '/traits'
  id:
    | '__root__'
    | '/'
    | '/async'
    | '/concurrency'
    | '/errors'
    | '/frontend'
    | '/lifetimes'
    | '/macros'
    | '/memory'
    | '/ownership'
    | '/playground'
    | '/quiz'
    | '/run'
    | '/smart-pointers'
    | '/testing'
    | '/traits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsyncRoute: typeof AsyncRoute
  ConcurrencyRoute: typeof ConcurrencyRoute
  ErrorsRoute: typeof ErrorsRoute
  FrontendRoute: typeof FrontendRoute
  LifetimesRoute: typeof LifetimesRoute
  MacrosRoute: typeof MacrosRoute
  MemoryRoute: typeof MemoryRoute
  OwnershipRoute: typeof OwnershipRoute
  PlaygroundRoute: typeof PlaygroundRoute
  QuizRoute: typeof QuizRoute
  RunRoute: typeof RunRoute
  SmartPointersRoute: typeof SmartPointersRoute
  TestingRoute: typeof TestingRoute
  TraitsRoute: typeof TraitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traits': {
      id: '/traits'
      path: '/traits'
      fullPath: '/traits'
      preLoaderRoute: typeof TraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-pointers': {
      id: '/smart-pointers'
      path: '/smart-pointers'
      fullPath: '/smart-pointers'
      preLoaderRoute: typeof SmartPointersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ownership': {
      id: '/ownership'
      path: '/ownership'
      fullPath: '/ownership'
      preLoaderRoute: typeof OwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros': {
      id: '/macros'
      path: '/macros'
      fullPath: '/macros'
      preLoaderRoute: typeof MacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifetimes': {
      id: '/lifetimes'
      path: '/lifetimes'
      fullPath: '/lifetimes'
      preLoaderRoute: typeof LifetimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontend': {
      id: '/frontend'
      path: '/frontend'
      fullPath: '/frontend'
      preLoaderRoute: typeof FrontendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurrency': {
      id: '/concurrency'
      path: '/concurrency'
      fullPath: '/concurrency'
      preLoaderRoute: typeof ConcurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/async': {
      id: '/async'
      path: '/async'
      fullPath: '/async'
      preLoaderRoute: typeof AsyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsyncRoute: AsyncRoute,
  ConcurrencyRoute: ConcurrencyRoute,
  ErrorsRoute: ErrorsRoute,
  FrontendRoute: FrontendRoute,
  LifetimesRoute: LifetimesRoute,
  MacrosRoute: MacrosRoute,
  MemoryRoute: MemoryRoute,
  OwnershipRoute: OwnershipRoute,
  PlaygroundRoute: PlaygroundRoute,
  QuizRoute: QuizRoute,
  RunRoute: RunRoute,
  SmartPointersRoute: SmartPointersRoute,
  TestingRoute: TestingRoute,
  TraitsRoute: TraitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
